In [1]:
import numpy as np 
a = np.array([1,2,3]) 
a

array([1, 2, 3])

In [2]:
a = np.array([[1, 2], [3, 4]]) 
a

array([[1, 2],
       [3, 4]])

In [3]:
a = np.array([1, 2, 3,4,5], ndmin = 2) 
a

array([[1, 2, 3, 4, 5]])

In [4]:
a = np.array([1, 2, 3,4,5], ndmin = 3) 
a

array([[[1, 2, 3, 4, 5]]])

In [5]:
a = np.array([1, 2, 3], dtype = complex) 
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
import numpy as np 
dt = np.dtype(np.int32) 
dt

dtype('int32')

In [8]:
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
a['age']

array([10, 20, 30], dtype=int8)

In [11]:
dt = np.dtype([('age',np.int8)]) 
a = np.array([10,20,30], dtype = dt) 
a['age']

array([10, 20, 30], dtype=int8)

In [15]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
student


dtype([('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [16]:
a = np.array([[1,2,3],[4,5,6]]) 
a.shape

(2, 3)

In [17]:
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
a 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
a.size
a.ndim

2

In [20]:
a = np.arange(5) 
a

array([0, 1, 2, 3, 4])

In [22]:
import numpy as np 
a = np.arange(24) 
print(a.ndim)  

# now reshape it 
b = a.reshape(2,4,3) 
b 

1


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [24]:
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int16) 
print (x.itemsize)

2


In [25]:
x = np.array([1,2,3,4,5]) 
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [26]:
x = np.empty([3,2], dtype = int) 
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
import numpy as np 
x = np.zeros(5) 
x

array([0., 0., 0., 0., 0.])

In [28]:
import numpy as np 
x = np.zeros((5,), dtype = np.int) 
x

array([0, 0, 0, 0, 0])

In [29]:
import numpy as np 
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
x

array([[(0, 0), (0, 0)],
       [(0, 0), (0, 0)]], dtype=[('x', '<i4'), ('y', '<i4')])

In [35]:
np.ones((3,),dtype=np.int8)

array([1, 1, 1], dtype=int8)

In [36]:
x = np.ones([2,2], dtype = int) 
x

array([[1, 1],
       [1, 1]])

In [37]:
x = [1,2,3] 
a = np.asarray(x) 
a

array([1, 2, 3])

In [38]:
np.asarray([1,2,3],dtype=float)

array([1., 2., 3.])

In [39]:
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
a

array([(1, 2, 3), (4, 5)], dtype=object)

In [40]:
s = 'Hello World' 
a = np.frombuffer(s, dtype = 'S1') 
a

AttributeError: ignored

In [45]:
list = np.arange(5) 
list

array([0, 1, 2, 3, 4])

In [46]:
list = range(5) 
it = iter(list)  

# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
x

array([0., 1., 2., 3., 4.])

In [47]:
x = np.arange(5) 
x

array([0, 1, 2, 3, 4])

In [48]:
x = np.arange(5, dtype = float)
x

array([0., 1., 2., 3., 4.])

In [49]:
x = np.arange(10,20,2) 
x

array([10, 12, 14, 16, 18])

In [50]:
x = np.linspace(10,20,5) 
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [51]:
x = np.linspace(1,2,5, retstep = True) 
x 

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

In [52]:
a = np.logspace(1.0, 2.0, num =5) 
a

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [56]:
x = np.linspace(1,10,10) 
print('line space',x)
a = np.logspace(1,10,num = 10, base = 2) 
a

line space [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [57]:
a = np.arange(10) 
s = slice(2,7,2) 
a[s]

array([2, 4, 6])

In [58]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a = np.arange(10) 
b = a[5] 
b

5

In [61]:
a = np.arange(10) 
print(a)
a[2:]

[0 1 2 3 4 5 6 7 8 9]


array([2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a = np.arange(10) 
a[2:5]

array([2, 3, 4])

In [65]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)

# slice items starting from index
print ('Now we will slice the array from the index a[1:]')
a[1:]

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]


array([[3, 4, 5],
       [4, 5, 6]])

In [76]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
a[0,0:]



array([1, 2, 3])

In [72]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
y

array([1, 4, 5])

In [78]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print ('Our array is:' )
print (x)


rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   

y

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  2],
       [ 9, 11]])

In [79]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])
x[:,[1,2]]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [81]:
x[x > 5]

array([ 6,  7,  8,  9, 10, 11])

In [82]:
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [85]:
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
a[np.isnan(a)]

array([nan, nan])

In [86]:
a = np.array([1, 2+6j, 5, 3.5+5j]) 
a[np.iscomplex(a)]

array([2. +6.j, 3.5+5.j])

In [92]:
[np.iscomplex(a)]

[array([False,  True, False,  True])]

In [93]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
c

array([ 10,  40,  90, 160])

In [94]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print (a) 
   
print ('Second array:') 
print (b) 
   
print ('First Array + Second Array') 
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Second array:
[1. 2. 3.]
First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [96]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print ('Original array is:')
print (a)

print ('Modified array is:')
for x in np.nditer(a):
   print (x,)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [97]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
   
print ('Original array is:')
print (a)
 
   
print ('Transpose of the original array is:') 
b = a.T 
print (b) 

   
print ('Modified array is:')
for x in np.nditer(b): 
   print (x,)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [98]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)


print ('Transpose of the original array is:')
b = a.T
print (b)


print ('Sorted in C-style order:')
c = b.copy(order = 'C')
print (c)
for x in np.nditer(c):
   print (x,)



print ('Sorted in F-style order:')
c = b.copy(order = 'F')
print (c)
for x in np.nditer(c):
   print (x,)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
Sorted in C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55
Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [99]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print ('Original array is:')
print (a) 
 

print ('Sorted in C-style order:') 
for x in np.nditer(a, order = 'C'): 
   print (x,)  
    

print ('Sorted in F-style order:' )
for x in np.nditer(a, order = 'F'): 
   print (x,)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Sorted in C-style order:
0
5
10
15
20
25
30
35
40
45
50
55
Sorted in F-style order:
0
20
40
5
25
45
10
30
50
15
35
55


In [100]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)


for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
print ('Modified array is:')
print (a)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [110]:
a = np.arange(8).reshape(2,4) 
print ('The original array:' )
print (a) 
 

print ('After applying the flat function:')
# returns element corresponding to index in flattened array 
print (a.flat[0:])

The original array:
[[0 1 2 3]
 [4 5 6 7]]
After applying the flat function:
[0 1 2 3 4 5 6 7]
